window.SS_WEEKS = [
{n:1,title:"Move Like a Badminton Player",sub:"Stage 1 - movement foundations",kit:"C, S",stage:1,
warmup:[
{t:"0:00-3:00",x:"Jog 2 laps; coach calls SPRINT for 5-second bursts (x4) between jogs",f:"Pulse raiser",refs:["Jog laps + sprint bursts"]},
{t:"3:00-4:00",x:"Walking circle: slow neck rolls (4 each way), shoulder shrugs & rolls (8)",f:"Head/shoulders",refs:["Neck rolls","Shoulder rolls & shrugs"]},
{t:"4:00-5:00",x:"Big arm circles forward/backward (8 each), wrist rolls both ways (10 each)",f:"Arms/wrists",refs:["Arm circles","Wrist rolls / figure-8s"]},
{t:"5:00-6:00",x:"Trunk twists (10), side bends (5 each side)",f:"Trunk",refs:["Trunk twists","Side bends"]},
{t:"6:00-7:30",x:"10 jumping jacks -> 6 side lunges each leg -> 10 back kicks on the spot",f:"Legs",refs:["Jumping jacks","Side lunges","Back kicks (heel flicks)"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Chasse sideways line-to-line x4 widths; teach ready position; freeze game",f:"Badminton footwork",refs:["Chasse widths","Ready-position freezes"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Line Tag - all kids on court lines, 3 taggers in bibs, rotate every 90s. Easier: walk only. Harder: chasse only",f:"Whole body + court lines",refs:["Line Tag"]}],
games:[{slot:"Game 1 (7 min)",n:"Beat the Keeper",id:"S1-MOV-01",grp:"4 teams of 5-6, two parallel games (throwers vs goalkeeper zone)",kit:"C,S",easier:"Bigger goal zone",harder:"Weaker-hand throws",sk:"Overarm throw = overhead hitting shape; keeper = interception + reading flight"},
{slot:"Game 2 (7 min)",n:"Shuttle/Cone Flip",id:"S1-MOV-11",grp:"2 teams of 10-11, whole hall flip race, 60s rounds",kit:"C",easier:"Fewer cones",harder:"Lunge to flip - no bending at the waist",sk:"Repeated lunging = lunge pattern; scanning = court awareness"}],
backup:{n:"Knee Tag",id:"S1-MOV-05",grp:"10-11 pairs",kit:"N",sk:"Low ready posture + reaction speed"},
notes:"T1 cones pre-set for both games. T4 colour teams at minute 0 - they persist into games and all term. T3 rehearse the freeze signal twice during the pulse raiser (week-1 investment). Brief Beat the Keeper with T2 during wrist rolls."},
{n:2,title:"Throw It Like a Clear",sub:"Stage 1 - overarm throw = overhead pattern",kit:"C, S",stage:1,
warmup:[
{t:"0:00-3:00",x:"Traffic lights jog: green jog, amber sidestep, red freeze in ready position, blue 3s sprint",f:"Pulse raiser + listening",refs:["Traffic lights jog"]},
{t:"3:00-4:00",x:"Neck rolls, shoulder rolls, slow-motion overarm throw shadows x8 each arm",f:"Head/shoulders",refs:["Neck rolls","Shoulder rolls & shrugs","Throw shadows"]},
{t:"4:00-5:00",x:"Arm circles small to big (10), wrist rolls (10), finger piano stretches",f:"Arms/wrists",refs:["Arm circles","Wrist rolls / figure-8s","Finger piano + squeezes"]},
{t:"5:00-6:00",x:"Trunk twists with arms out (10), hip circles (5 each way)",f:"Trunk",refs:["Trunk twists","Hip circles / openers"]},
{t:"6:00-7:30",x:"8 front lunges alternating -> 10 high knees -> 10 back kicks",f:"Legs",refs:["Front lunges","High knees","Back kicks (heel flicks)"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Chasse recap x2 widths, add PIVOT on coach's clap; 5 ready-position freezes",f:"Badminton footwork",refs:["Chasse widths","Pivot on clap","Ready-position freezes"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Shuttle Dodge - two games of 10-11 (throwers ring a zone, dodgers evade), swap every 90s. Easier: bigger zone. Harder: dodgers must chasse",f:"Whole body + evasion",refs:["Shuttle Dodge"]}],
games:[{slot:"Game 1 (7 min)",n:"Tramline Throwbacks",id:"S1-RAC-12",grp:"10-11 pairs across tramlines/net; PB: most catches in 60s",kit:"S",easier:"Stand closer together",harder:"Throw from a lunge, one-handed catch",sk:"Overarm throw grooves the full overhead clear action"},
{slot:"Game 2 (7 min)",n:"Player in the Middle",id:"S1-MOV-08",grp:"4 groups of 5-6 (4 passers + 1-2 interceptors, rotate every 60s)",kit:"S",easier:"Middle player only needs a touch",harder:"Two in the middle",sk:"Interception, reading flight paths, quick feet"}],
backup:{n:"Throw & Catch Rallies",id:"S1-RLY-07",grp:"10-11 pairs",kit:"S",sk:"Rally rhythm + shuttle tracking before rackets appear"},
notes:"Deliberately low-kit week (shuttles + lines only) - good early-term insurance. T7 to pair instantly for Throwbacks. T8: odd child joins a Player-in-the-Middle group as second interceptor."},
{n:3,title:"Racket in Hand",sub:"Stage 1 - grip, control, first hits",kit:"C, H, P, R, S",stage:1,
warmup:[
{t:"0:00-3:00",x:"Follow-the-coach jog snake: coach weaves, adds skips, sidesteps, 2 sprint bursts",f:"Pulse raiser",refs:["Follow-the-coach snake"]},
{t:"3:00-4:30",x:"Shoulder rolls, arm circles; racket wrists: shake-hands grip check, imaginary-racket wrist rolls, 'swat the fly' flicks x10",f:"Shoulders/wrists (grip prep)",refs:["Shoulder rolls & shrugs","Arm circles","Wrist rolls / figure-8s"]},
{t:"4:30-6:00",x:"Trunk twists (10), side lunges x6 each leg",f:"Trunk + legs",refs:["Trunk twists","Side lunges"]},
{t:"6:00-7:30",x:"10 jumping jacks -> 8 front lunges -> 10 high knees",f:"Legs",refs:["Jumping jacks","Front lunges","High knees"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Chasse + pivot recap, then first split-step taster: coach claps, kids bounce into ready position x8",f:"Badminton footwork",refs:["Pivot on clap","Split-step bounce"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Jump to It - directional jump calls (fwd/back/left/right/180); last to react does 2 star jumps. Easier: slower calls. Harder: silent pointing, react to sight",f:"Legs/landing + reaction",refs:["Jump to It"]}],
games:[{slot:"Game 1 (7 min)",n:"Shuttle Scoop (relay format)",id:"S1-RAC-10",grp:"4 relay teams of 5-6: scoop shuttle off floor with racket, carry, deposit in hoop",kit:"R,S,H",easier:"Hand-assist the scoop",harder:"Scoop with backhand face",sk:"Racket-face control + relaxed grip"},
{slot:"Game 2 (7 min)",n:"Forehand Taps Foam Pads",id:"S1-RAC-08",grp:"10-11 pairs: one holds pad, one taps; PB taps in 30s, swap",kit:"R,S,P",easier:"Bigger pad / stand closer",harder:"Alternate FH/BH taps",sk:"Forehand contact point + soft hands"}],
backup:{n:"Tap Ups PB ladder (5-10-20)",id:"S1-RAC-11",grp:"Every child, individual",kit:"R,S",sk:"Hand-eye + grip; zero setup - perfect low-kit fallback"},
notes:"First racket week: team captains collect 5-6 rackets each (never 21 kids at one bag), T6 countdown. RECORD week-3 Tap Ups PB scores - this is the baseline re-tested in week 12."},
{n:4,title:"Throwminton Festival",sub:"Stage 1 consolidation - matchplay week",kit:"C, R, S",stage:1,
warmup:[
{t:"0:00-3:00",x:"Shuttle-run pulse raiser: jog to net, backpedal to baseline x4, then 2 sprint widths",f:"Pulse raiser + backward movement",refs:["Shuttle-run + backpedal"]},
{t:"3:00-4:30",x:"Neck rolls, arm circles, wrist rolls, throw shadows x8",f:"Head/arms/wrists",refs:["Neck rolls","Arm circles","Wrist rolls / figure-8s","Throw shadows"]},
{t:"4:30-6:00",x:"Trunk twists, hip circles, side lunges x6 each",f:"Trunk + legs",refs:["Trunk twists","Hip circles / openers","Side lunges"]},
{t:"6:00-7:30",x:"10 back kicks -> 8 front lunges -> 10 jumping jacks",f:"Legs",refs:["Back kicks (heel flicks)","Front lunges","Jumping jacks"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Teach the four calls of Change or Twist slowly (chasse L/R, pivot, twist) as the footwork block",f:"Badminton footwork",refs:["Change or Twist"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Change or Twist at full speed; last to react does bunny hops. Easier: 2 calls only. Harder: add jump + lunge calls",f:"Whole body + movement vocab",refs:["Change or Twist"]}],
games:[{slot:"Big game (14 min)",n:"Team Jailbreak",id:"S1-MAT-07",grp:"2 simultaneous games of ~10 v 11 on adjacent courts; swap roles at 7 min",kit:"R,S,C",easier:"Throw instead of hit",harder:"Must hit with racket; catchers one-handed",sk:"Court coverage, teamwork, sending the shuttle to space (tactical seed)"}],
backup:{n:"Catch Badminton",id:"S1-RLY-01",grp:"10-11 pairs over nets",kit:"S",sk:"Full game shape (serve, rally, point) with zero racket barrier"},
notes:"Announce FESTIVAL WEEK at minute 0 - colour teams from weeks 1-3 now compete for the term's Team Cup. One brief for both Jailbreak courts at once (T2/T5); swap halves at 7 min so every child plays both roles."},
{n:5,title:"Serve It Up",sub:"Stage 2 begins - high & low serves",kit:"C, H, R, S",stage:2,
warmup:[
{t:"0:00-3:00",x:"Pairs jog; on whistle the back partner sprints to the front x6",f:"Pulse raiser",refs:["Pairs overtaking jog"]},
{t:"3:00-4:30",x:"Shoulder rolls, big arm swings across chest, wrist rolls, underarm serve shadows x8",f:"Shoulders/arms/wrists",refs:["Shoulder rolls & shrugs","Arm circles","Wrist rolls / figure-8s","Underarm serve shadows"]},
{t:"4:30-6:00",x:"Trunk twists, hamstring sweeps x6 each, side lunges x6",f:"Trunk + legs",refs:["Trunk twists","Hamstring sweeps","Side lunges"]},
{t:"6:00-7:30",x:"10 high knees -> 10 back kicks -> 8 front lunges with arm reach",f:"Legs",refs:["High knees","Back kicks (heel flicks)","Front lunges"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Split-step development: partner points left/right, split-step then chasse that way x8, swap",f:"Badminton footwork",refs:["Partner-point split-step"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Chain Tag - 2 taggers, tagged join hands (max chain 3 then split). Easier: chains of 2. Harder: chains must chasse",f:"Whole body + agility",refs:["Chain Tag"]}],
games:[{slot:"Game 1 (7 min)",n:"Forehand High Serve Relay",id:"S1-RAC-06",grp:"4 relay teams of 5-6: serve over net into team target zone, run to back",kit:"R,S,C",easier:"Bigger/closer zone",harder:"Zone at the rear tramlines",sk:"Forehand high serve - full swing + weight transfer"},
{slot:"Game 2 (7 min)",n:"Push the Birdie",id:"S1-RAC-09",grp:"10-11 pairs at the net: BH low serve at floor targets; PB hits in 5 attempts",kit:"R,S,C",easier:"Hand-feed push",harder:"Serve must skim a string/cone gate",sk:"Backhand low serve - the most used junior shot"}],
backup:{n:"Throw Golf",id:"S2-MOV-10",grp:"4 teams of 5-6 around hoop holes",kit:"S,C,H",sk:"Trajectory judgement + throwing accuracy"},
notes:"Stage 2 step-up week - keep one familiar Stage 1 game (the relay) so the only new brief is Push the Birdie (T5 30-second demo at the net while teams jog a lap). Targets pre-set (T1)."},
{n:6,title:"Rally Builders",sub:"Stage 2 - lifts + first sustained rallies",kit:"C, R, S",stage:2,
warmup:[
{t:"0:00-3:00",x:"Countdown jog: coach calls 1-4 = that many jumping jacks mid-jog; ZERO = sprint to a wall and back",f:"Pulse raiser + listening",refs:["Countdown jacks jog"]},
{t:"3:00-4:30",x:"Arm circles, shoulder shrugs, wrist figure-8s, underarm lift shadows x8 each side",f:"Arms/wrists",refs:["Arm circles","Shoulder rolls & shrugs","Wrist rolls / figure-8s","Underarm serve shadows"]},
{t:"4:30-6:00",x:"Trunk twists, hip openers (gate open/close x6 each)",f:"Trunk/hips",refs:["Trunk twists","Hip circles / openers"]},
{t:"6:00-7:30",x:"Side lunges x6 -> front lunges x6 -> 10 back kicks",f:"Legs",refs:["Side lunges","Front lunges","Back kicks (heel flicks)"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Lunge patterns: chasse forward + lunge as if to a net kill x6 each side, recover backwards",f:"Badminton footwork",refs:["Lunge patterns"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Change Twist Jump Lunge at speed; 5-in-a-row earns 'coach for 30 seconds'. Easier: 3 calls. Harder: silent gestures only",f:"Whole body - full movement vocab",refs:["Change Twist Jump Lunge"]}],
games:[{slot:"Game 1 (7 min)",n:"Forehand Lift Rocket Launch",id:"S1-RAC-07",grp:"4 teams of 5-6, team race: lift shuttles high and deep into scoring zones",kit:"R,S,C",easier:"Hand-feed",harder:"Must launch from a lunge position",sk:"Underarm forehand lift - height + depth"},
{slot:"Game 2 (7 min)",n:"Bump (rally ladder)",id:"S2-RAC-06",grp:"Whole group: ~10 mini-court stations up the hall; winner bumps up, loser stays",kit:"R,S,C",easier:"Throw-catch rally at bottom stations",harder:"BH-only rallies at top stations",sk:"Rally consistency under light pressure; self-organised matchplay"}],
backup:{n:"Rally 1,2,3",id:"S1-RLY-03",grp:"10-11 pairs, step back on success",kit:"R,S",sk:"Rally length + adjusting power to distance"},
notes:"Bump is self-refereeing - invest 60 seconds in the 'how to bump' brief, then it runs itself while you float and coach individuals. Station markers pre-set (T1); pairs via T7."},
{n:7,title:"Net Play Ninjas",sub:"Stage 2 - soft hands at the net + reactions",kit:"C, H, R, S",stage:2,
warmup:[
{t:"0:00-3:00",x:"Sidestep pulse raiser: chasse 2 widths, jog 1 lap, chasse 2 widths, 3 sprint bursts",f:"Pulse raiser + chasse volume",refs:["Sidestep pulse raiser"]},
{t:"3:00-4:30",x:"Neck rolls, arm circles, slow-fast wrist rolls, finger squeezes (soft-hands prep)",f:"Head/arms/wrists",refs:["Neck rolls","Arm circles","Wrist rolls / figure-8s","Finger piano + squeezes"]},
{t:"4:30-6:00",x:"Trunk twists, side bends, hip circles",f:"Trunk",refs:["Trunk twists","Side bends","Hip circles / openers"]},
{t:"6:00-7:30",x:"10 jumping jacks -> side lunges x6 -> low net-lunge holds 3s x4 each leg",f:"Legs (lunge emphasis)",refs:["Jumping jacks","Side lunges","Net-lunge holds"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Split-step + forward lunge to an imaginary net shot x8; recover with 2 backward chasses",f:"Badminton footwork",refs:["Lunge patterns","Split-step bounce"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: 3 Player Knee Tag - trios all tag and dodge at once; rotate trios every 90s. Easier: pairs. Harder: stay in low ready posture",f:"Whole body + low posture",refs:["3 Player Knee Tag"]}],
games:[{slot:"Game 1 (7 min)",n:"Beat the Keeper - Racquet Edition",id:"S2-MOV-03",grp:"4 teams of 5-6, two parallel games: hit past the keeper into a zone",kit:"R,S,C",easier:"Throw instead of hit",harder:"Nominate FH or BH before each hit",sk:"Placement + disguise; keeper trains reactions/interception"},
{slot:"Game 2 (7 min)",n:"Forecourt Domination (rotation)",id:"S1-MAT-02",grp:"Pairs on half-courts, forecourt-only points; waiting kids = ball-kids/scorers on strict 60s rotation",kit:"R,S",easier:"Throw-catch forecourt",harder:"BH-only variant",sk:"Net shots, soft hands, forecourt dominance"}],
backup:{n:"Golfminton",id:"S2-MAT-04",grp:"4 teams of 5-6 touring hoop holes",kit:"R,S,C,H",sk:"Controlled soft hitting + trajectory"},
notes:"Forecourt Domination with 20+ kids only works with strict rotation - T6 countdowns every 60s. If courts are short, run game 1 on the hall floor and game 2 on available nets, swap halves at 7 min."},
{n:8,title:"Mid-Term Games Festival",sub:"Stage 2 consolidation - matchday week",kit:"C, R, S",stage:2,
warmup:[
{t:"0:00-3:00",x:"Captains' choice pulse raiser: each captain picks one move (jog/skip/sidestep/sprint), 45s each",f:"Pulse raiser + ownership",refs:["Captains' choice"]},
{t:"3:00-4:30",x:"Arm circles, wrist rolls, throw + lift shadows x6 each",f:"Arms/wrists",refs:["Arm circles","Wrist rolls / figure-8s","Throw shadows","Underarm serve shadows"]},
{t:"4:30-6:00",x:"Trunk twists, hamstring sweeps, hip openers",f:"Trunk",refs:["Trunk twists","Hamstring sweeps","Hip circles / openers"]},
{t:"6:00-7:30",x:"Jumping jacks x10 -> front lunges x6 -> back kicks x10 -> high knees x10 (full leg medley)",f:"Legs",refs:["Jumping jacks","Front lunges","Back kicks (heel flicks)","High knees"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Back Track patterns: jog forward 4 steps, backpedal to start, recover to ready x6; split-step on clap",f:"Badminton footwork + rear-court recovery",refs:["Back Track patterns"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Mirror Me Fourcourt - leader moves through four quadrants, partner mirrors; swap on whistle. Easier: walking. Harder: badminton moves only",f:"Whole body + anticipation",refs:["Mirror Me Fourcourt"]}],
games:[{slot:"Big game (14 min)",n:"Jailbreak",id:"S2-MAT-05",grp:"Whole group, one arena (or 2 halves of 10-11); rescue rule means nobody sits out longer than ~60s",kit:"R,S,C",easier:"Throw version",harder:"Nominated-shot hits only",sk:"Serving/hitting under pressure + team tactics; rescue rule secretly maximises movement volume"}],
backup:{n:"Serve Tug o War",id:"S2-MAT-06",grp:"10-11 pairs duelling across courts",kit:"R,S,C",sk:"Serve depth control; needs almost no space coordination - perfect chaos-day fallback"},
notes:"Festival week 2 - update Team Cup standings loudly at minute 0 (30 seconds, huge engagement). Jailbreak brief is the term's longest (rescue rule): T2 during the leg medley + demo one full jailbreak with a captain. Swap roles at 7 min."},
{n:9,title:"Split-Step & Fast Feet",sub:"Stage 3 begins - movement precision",kit:"C, L, R, S",stage:3,
warmup:[
{t:"0:00-3:00",x:"Jog with 5-second quick-feet bursts on the whistle x5, plus 2 sprints",f:"Pulse raiser",refs:["Quick-feet bursts"]},
{t:"3:00-4:30",x:"Neck rolls, arm circles, wrist figure-8s, overhead reach + drop shadows",f:"Head/arms/wrists",refs:["Neck rolls","Arm circles","Wrist rolls / figure-8s"]},
{t:"4:30-6:00",x:"Trunk twists, side bends, hip circles",f:"Trunk",refs:["Trunk twists","Side bends","Hip circles / openers"]},
{t:"6:00-7:30",x:"Side lunges x6 -> front lunges x6 -> 10 jumping jacks with 'quiet landings' cue",f:"Legs + landing mechanics",refs:["Side lunges","Front lunges","Jumping jacks"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Split-step masterclass: clap = split-step; clap + point = split-step then chasse that way x10",f:"Badminton footwork",refs:["Split-step bounce","Partner-point split-step"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Split-Step Square - 4 cone squares, 5-6 kids each, directional split-step reactions; PB correct reactions in 30s. Easier: slower calls. Harder: silent signals + fake-outs",f:"Legs/feet - signature skill",refs:["Split-Step Square"]}],
games:[{slot:"Game 1 (7 min)",n:"Tap Ups with a Twist",id:"S3-RAC-12",grp:"All 20-22 kids individually: continuous tap-ups; commands interrupt (star jumps, fast feet, sit down)",kit:"R,S",easier:"Catch between commands",harder:"Alternate FH/BH faces, one-leg taps",sk:"Racket control under fatigue + reaction to calls"},
{slot:"Game 2 (7 min)",n:"Tramline Ladders (relay format)",id:"S3-MOV-09",grp:"4 relay teams of 5-6: agility-ladder patterns then sprint-return",kit:"L",easier:"Simple 1-in runs (tramlines only if no ladders)",harder:"In-in-out, sideways patterns",sk:"Foot speed + rhythm; secretly trains chasse cadence"}],
backup:{n:"Spot Tap",id:"S3-MOV-08",grp:"4 groups of 5-6, numbered spots",kit:"C,R",sk:"Lunge + recover to base - core badminton movement"},
notes:"Stage 3 step-up: Tap Ups with a Twist needs zero grouping (T5 - start in 15 seconds), which buys time to lay ladders for game 2 while they play. With 21 kids: relay teams 5-5-5-6 (T8)."},
{n:10,title:"Attack the Net",sub:"Stage 3 - net kills, flicks, forecourt attack",kit:"C, P, R, S",stage:3,
warmup:[
{t:"0:00-3:00",x:"Jog + net-attack bursts: sprint 3 steps to an imaginary net and freeze in a lunge x5",f:"Pulse raiser",refs:["Net-attack bursts"]},
{t:"3:00-4:30",x:"Shoulder rolls, arm circles, fast wrist flicks ('flick the light switch') x10 each way",f:"Arms/wrists (flick prep)",refs:["Shoulder rolls & shrugs","Arm circles","Flick-the-switch wrist flicks"]},
{t:"4:30-6:00",x:"Trunk twists, hip openers, side bends",f:"Trunk",refs:["Trunk twists","Hip circles / openers","Side bends"]},
{t:"6:00-7:30",x:"High knees x10 -> back kicks x10 -> alternating front lunges with reach x8",f:"Legs",refs:["High knees","Back kicks (heel flicks)","Front lunges"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Split-step + attack-lunge combo to the 4 corners of a cone square x2 rounds",f:"Badminton footwork",refs:["Four-corner combo"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Hi-Low Amigo - partner holds pads high/low, mover split-steps and jump-touches or lunge-touches; 45s swaps. Easier: no split-step. Harder: partner fakes",f:"Whole body - jump + lunge + split-step",refs:["Hi-Low Amigo"]}],
games:[{slot:"Game 1 (7 min)",n:"Net Kill Skittles",id:"S3-RAC-01",grp:"4 teams of 5-6, two stations: feed above tape, kill down at shuttle-tube skittles; rotate hitter every 3 goes",kit:"R,S,C",easier:"Higher feed, closer skittles",harder:"BH net kills, smaller targets",sk:"Net kill - the downward attacking finish"},
{slot:"Game 2 (7 min)",n:"Backhand Flick Relay",id:"S3-RAC-02",grp:"4 relay teams of 5-6: BH flick over net/into deep zone, retrieve, tag next runner",kit:"R,S,C",easier:"Shorter flick zone",harder:"Flick must land beyond a depth line",sk:"Backhand flick - wrist power + disguise"}],
backup:{n:"Forecourt Domination Bingo",id:"S2-MAT-03",grp:"Pairs on half-courts with bingo cards",kit:"R,S,C",sk:"Placement variety in the forecourt"},
notes:"Skittle setup is fiddly - pre-build both stations (T1) and protect them with a no-go cone ring during the warmup. Rotate stations at 7 min with a T6 countdown - teams walk to the other station, zero re-brief. STRETCH swap if group is flying: S4 Direct the Shuttle BINGO game."},
{n:11,title:"Rally Like a Pro",sub:"Stage 3 - rally height control + consistency",kit:"R, S",stage:3,
warmup:[
{t:"0:00-3:00",x:"Pairs shadow-jog (leader/follower swap on whistle), 3 sprint bursts",f:"Pulse raiser",refs:["Pairs shadow-jog"]},
{t:"3:00-4:30",x:"Neck rolls, arm circles, wrist rolls, clear + drop shadow swings x6 each",f:"Head/arms/wrists",refs:["Neck rolls","Arm circles","Wrist rolls / figure-8s","Throw shadows"]},
{t:"4:30-6:00",x:"Trunk twists, hamstring sweeps, hip circles",f:"Trunk",refs:["Trunk twists","Hamstring sweeps","Hip circles / openers"]},
{t:"6:00-7:30",x:"Jumping jacks x10 -> side lunges x6 -> front lunges x6 -> back kicks x10",f:"Legs",refs:["Jumping jacks","Side lunges","Front lunges","Back kicks (heel flicks)"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Full sequence: split-step -> chasse -> lunge -> recover, 4 corners, x2 rounds each side",f:"Badminton footwork",refs:["Full movement chain"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Simon Says (court-area edition) - 'Simon says chasse to the tramlines... split-step... 5 fast feet'; fitness forfeits. Easier: no eliminations. Harder: kids take turns as Simon",f:"Whole body + court geography",refs:["Simon Says"]}],
games:[{slot:"Game 1 (7 min)",n:"High Rally vs Low Rally (split stations)",id:"S3-RLY-04",id2:"S3-RLY-06",grp:"10-11 pairs: half on High Rally (above net-reach), half on Low Rally (below tape); swap at 3.5 min; PB counts recorded",kit:"R,S",easier:"Bigger height tolerance",harder:"Rally must alternate FH/BH",sk:"Trajectory control - the difference between lift/clear and drive/net game"},
{slot:"Game 2 (7 min)",n:"Team Singles",id:"S3-MAT-06",grp:"2 courts, 2 teams of 5-6 per court queued at each baseline: one rally then back of the queue",kit:"R,S",easier:"Serve restarts after 2 misses",harder:"Winner's team scores rally-length bonus",sk:"Singles matchplay at high participation - no child idle more than ~30s"}],
backup:{n:"Flat Rally Challenge",id:"S3-RLY-03",grp:"10-11 pairs, drives below head height",kit:"R,S",sk:"Fast flat drives + grip changes"},
notes:"Record PB rally counts via a team captain holding your phone/notepad - feeds the week-12 retest and the Session Tracker. Team Singles queues self-run; your job is umpiring energy, not admin. STRETCH swap: S5 Beautiful Backhands BUMP ladder."},
{n:12,title:"Champions' Festival",sub:"Stage 3 consolidation + PB retest + finale",kit:"C, H, R, S",stage:3,
warmup:[
{t:"0:00-3:00",x:"Greatest-hits pulse raiser: traffic lights (wk2) + countdown jacks (wk6) mashup - zero briefing needed",f:"Pulse raiser",refs:["Traffic lights jog","Countdown jacks jog"]},
{t:"3:00-4:30",x:"Full arm sequence: neck rolls, shoulder rolls, arm circles, wrist figure-8s, throw/lift/flick shadows",f:"Head/arms/wrists",refs:["Neck rolls","Shoulder rolls & shrugs","Arm circles","Wrist rolls / figure-8s","Throw shadows","Flick-the-switch wrist flicks"]},
{t:"4:30-6:00",x:"Trunk twists, side bends, hip openers",f:"Trunk",refs:["Trunk twists","Side bends","Hip circles / openers"]},
{t:"6:00-7:30",x:"Leg medley: jacks x10, side lunges x6, front lunges x6, high knees x10, back kicks x10",f:"Legs",refs:["Jumping jacks","Side lunges","Front lunges","High knees","Back kicks (heel flicks)"]},
{t:"7:30 +15s",x:"MICRO-BREAK: shake out arms and legs, 3 deep breaths",f:"Recovery",br:1},
{t:"7:30-10:00",x:"Footwork showcase: full split-step -> chasse -> lunge -> recover; kids demo in fours to applause",f:"Badminton footwork",refs:["Full movement chain"]},
{t:"10:00 +20s",x:"WATER SIP while coach explains the fun finisher (T2 - demo as they drink)",f:"Hydration + brief",br:1},
{t:"10:00-15:00",x:"FUN FINISHER: Landing Zone - directional jumps into hoops/zones, 'silent landings' scored; final round = kids vote for the term's favourite finisher",f:"Whole body + landing quality",refs:["Landing Zone"]}],
games:[{slot:"Big game (11 min)",n:"Up-Down-Net-Retreat doubles ladder",id:"S3-MAT-08",grp:"All courts: doubles pairs ladder, winners up a court, losers down; 90-second timed rounds (~6 mini-matches each)",kit:"R,S",easier:"Throw-serve starts",harder:"Top court plays Danish scoring (service box only)",sk:"Full matchplay: scoring, positioning, everything from weeks 1-11"},
{slot:"PB retest (4 min)",n:"Tap Ups PB retest",id:"S1-RAC-11",grp:"All kids simultaneously: 60s tap-ups PB attempt x2; compare with week-3 baseline",kit:"R,S",easier:"-",harder:"-",sk:"Visible proof of progress - the retention message to kids and parents"}],
backup:{n:"Pack of Cards",id:"S3-MAT-04",grp:"Pairs chasing hidden card target scores",kit:"R,S",sk:"Scoreboard pressure + rally focus (needs playing cards); Pampas rotating doubles if courts are limited"},
notes:"Award the Team Cup at 29:30 sharp - hand over to the lead coach on a high. Pre-write the courts ladder order (T1). The PB retest is the emotional payoff of the term: announce baseline beats individually by name."}
];
window.SS_KIT = {N:"No equipment",C:"Cones / spots / lines",S:"Shuttles",R:"Rackets",P:"Foam pads",H:"Hoops",L:"Agility ladders"};
